import './site.css';
const root=document.querySelector<HTMLDivElement>('#docs-root')!;
const L={en:{title:'Great Britain API Docs',sub:'UPRN-first property identity with deterministic HMLR enrichment where the official links exist.',quick:'Quickstart',auth:'Authentication',property:'Property lookup',response:'Response contract',coverage:'Coverage behaviour',errors:'Errors & retries',rights:'Rights & provenance',workspace:'Open workspace'},cy:{title:'Dogfennau API Prydain Fawr',sub:'Hunaniaeth eiddo UPRN gyda chyfoethogi HMLR pendant lle mae dolenni swyddogol ar gael.',quick:'Cychwyn cyflym',auth:'Dilysu',property:'Chwilio eiddo',response:'Contract ymateb',coverage:'Ymddygiad cwmpas',errors:'Gwallau ac ailgeisio',rights:'Hawliau a tharddiad',workspace:'Agor gweithle'}} as const;
type Lang=keyof typeof L;
root.innerHTML=`<header class="sub-header"><div class="shell sub-nav"><a class="brand" href="/"><span class="brandmark"><span></span></span><span><b>PropData</b><small>GREAT BRITAIN · DOCS</small></span></a><a href="/">Home</a><a href="/workspace">Workspace</a><a href="/#pricing">Pricing</a><div class="lang-switch"><button class="lang-btn active" data-lang="en">EN</button><button class="lang-btn" data-lang="cy">CY</button></div></div></header><main class="sub-main"><section class="sub-hero"><div><span class="kicker">PROPDATA GB · REST API</span><h1 data-k="title">Great Britain API Docs</h1><p data-k="sub">UPRN-first property identity with deterministic HMLR enrichment where the official links exist.</p><div class="api-cta-row"><a class="btn primary darkbtn" href="/workspace" data-k="workspace">Open workspace</a><a class="btn outline" href="/#pricing">Get API access</a></div></div><div class="sub-art"><img src="/images/property-graph.webp" alt="PropData GB property graph"></div></section><div class="docs-layout"><aside class="docs-sidebar"><b>GB API</b><a href="#quick" data-k="quick">Quickstart</a><a href="#auth" data-k="auth">Authentication</a><a href="#property" data-k="property">Property lookup</a><a href="#response" data-k="response">Response contract</a><a href="#coverage" data-k="coverage">Coverage behaviour</a><a href="#errors" data-k="errors">Errors & retries</a><a href="#rights" data-k="rights">Rights & provenance</a></aside><article class="docs-content">
<section id="quick"><h2 data-k="quick">Quickstart</h2><p>The certified GB launch route is <span class="inline-code">GET /v1/property</span> with <span class="inline-code">country=GB</span> and an official UPRN. The response keeps property identity separate from optional HMLR enrichment.</p><pre class="doc-code">curl -G 'https://propdata-api-worker.sales-fd3.workers.dev/v1/property' \\
  -H 'x-api-key: $PROPDATA_API_KEY' \\
  --data-urlencode 'country=GB' \\
  --data-urlencode 'uprn=10090718379'</pre><div class="callout">Use the Workspace to run this request against production without storing your API key in the page.</div></section>
<section id="auth"><h2 data-k="auth">Authentication</h2><p>REST requests require your PropData key in the <span class="inline-code">x-api-key</span> request header. Keep production credentials in server-side secrets or environment variables. Do not place them in a URL, browser bundle, repository, screenshot or analytics payload.</p><pre class="doc-code">x-api-key: $PROPDATA_API_KEY</pre><p>For account usage and limits, new integrations should prefer <span class="inline-code">GET /v1/auth/usage</span>. MCP uses OAuth and a separate authorization flow; do not reuse REST-key instructions for MCP.</p></section>
<section id="property"><h2 data-k="property">Property lookup</h2><h3>GET /v1/property</h3><table class="param-table"><thead><tr><th>Parameter</th><th>Required</th><th>GB contract</th></tr></thead><tbody><tr><td><span class="mono">country</span></td><td>Yes</td><td>Use <span class="inline-code">GB</span></td></tr><tr><td><span class="mono">uprn</span></td><td>Yes for GB launch route</td><td>Official Unique Property Reference Number</td></tr><tr><td><span class="mono">enrich</span></td><td>No</td><td><span class="inline-code">standard</span> is supported in the certified property resolver</td></tr></tbody></table><h3>Verified examples</h3><table class="param-table"><tbody><tr><td>Wales</td><td><span class="mono">10090718379</span></td><td>Transaction + registered extent + indicative value</td></tr><tr><td>London</td><td><span class="mono">100021809877</span></td><td>Transaction + indicative value; extent may be unavailable</td></tr><tr><td>Birmingham</td><td><span class="mono">100070359270</span></td><td>Leasehold example with linked HMLR transaction</td></tr><tr><td>Scotland</td><td><span class="mono">10025270278</span></td><td>Exact UPRN identity; HMLR-specific layers correctly unavailable</td></tr></tbody></table></section>
<section id="response"><h2 data-k="response">Response contract</h2><p>A successful exact UPRN match can include the following top-level property fields. Optional fields are coverage-dependent and must not be treated as guaranteed.</p><pre class="doc-code">{
  "country_code": "GB",
  "match_level": "uprn_exact",
  "confidence": 100,
  "property_id_type": "UPRN",
  "property_id": "10090718379",
  "coordinates": { "latitude": 51.50, "longitude": -3.14 },
  "source_ids": { "uprn": "...", "toids": [], "usrns": [] },
  "coverage": { "property_identity": "available", "transactions": "..." },
  "transactions": [ ... ],
  "registered_extent_polygons": [ ... ],
  "indicative_valuation": { ... },
  "provenance": [ ... ]
}</pre><p>Identity fields are factual source records. The indicative valuation is a PropData market signal and should not be presented as a lender-grade appraisal or official valuation.</p></section>
<section id="coverage"><h2 data-k="coverage">Coverage behaviour</h2><p>Great Britain property identity comes from the loaded OS Open UPRN layer. HM Land Registry Price Paid and INSPIRE enrichment is an England & Wales layer and only appears when the official transaction lookup tables provide deterministic links.</p><div class="callout"><b>Fail-open rule:</b> missing HMLR enrichment does not invalidate a real UPRN. A Scottish property can return exact identity, coordinates and linked OS identifiers while transactions, INSPIRE extent and valuation remain unavailable.</div><p>Always inspect the response <span class="inline-code">coverage</span> object and <span class="inline-code">provenance</span> array. Do not infer that unavailable means negative or absent in the real world.</p></section>
<section id="errors"><h2 data-k="errors">Errors & retries</h2><table class="param-table"><tbody><tr><td>401</td><td>Missing or invalid API key</td><td>Fix credentials; do not retry indefinitely</td></tr><tr><td>429</td><td>Quota / rate limit</td><td>Back off and inspect account usage</td></tr><tr><td>5xx</td><td>Temporary resolver/upstream failure</td><td>Retry with bounded exponential backoff</td></tr><tr><td>200 + no match</td><td>No verified property for requested identifier</td><td>Do not invent a candidate match</td></tr></tbody></table><p>Production clients should use bounded retry, preserve idempotency for writes elsewhere in the platform, and distinguish no-match from unavailable enrichment.</p></section>
<section id="rights"><h2 data-k="rights">Rights & provenance</h2><p>The GB stack combines Ordnance Survey OS Open UPRN / linked identifier sources and HM Land Registry Price Paid / official transaction lookup / INSPIRE sources. Source names remain visible in API provenance.</p><div class="callout">HMLR Price Paid address fields carry separate third-party restrictions. The certified canonical transaction graph intentionally excludes those restricted address fields. INSPIRE geometry is an indicative registered freehold extent and is not a legal title boundary.</div><p>Support: <a href="mailto:sales@proptechusa.ai">sales@proptechusa.ai</a></p></section>
</article></div></main>`;
function lang(x:Lang){document.documentElement.lang=x==='cy'?'cy-GB':'en-GB';document.querySelectorAll<HTMLElement>('[data-k]').forEach(el=>{const k=el.dataset.k as keyof typeof L.en;const v=L[x][k];if(v)el.textContent=v});document.querySelectorAll<HTMLButtonElement>('.lang-btn').forEach(b=>b.classList.toggle('active',b.dataset.lang===x));localStorage.setItem('propdata-gb-lang',x)}
const saved=(localStorage.getItem('propdata-gb-lang')||'en') as Lang;lang(saved==='cy'?'cy':'en');document.querySelectorAll<HTMLButtonElement>('.lang-btn').forEach(b=>b.addEventListener('click',()=>lang((b.dataset.lang||'en') as Lang)));
