const STRIPE={developer:'https://buy.stripe.com/4gM8wP1rUfKS4pv5sn7wA0g',builder:'https://buy.stripe.com/8x29ATgmOaqy4pvg717wA0h',scale:'https://buy.stripe.com/00w5kDfiK1U21djaMH7wA0i'};

type Lang='en'|'cy';
const text={
  en:{hero1:'Great Britain',hero2:'Property Intelligence.',sub:'One UPRN. One source-aware property graph.',body:'Resolve a Great Britain property by its official UPRN, then attach coordinates, linked OS identifiers and - across England & Wales where HMLR provides deterministic links - recorded transactions, tenure, property type, registered-extent geometry and indicative valuation.',product:'Product',coverage:'Coverage',docs:'Docs',workspace:'API Workspace',pricing:'Pricing',sources:'Sources',access:'Get GB access',start:'Start Developer',viewDocs:'View docs',openWorkspace:'Open workspace',priceTitle:'Production access in GBP.',priceBody:'Three self-serve GB plans. Secure hosted checkout by Stripe. Upgrade as volume grows.',proof:'Built like infrastructure, not a demo.'},
  cy:{hero1:'Prydain Fawr',hero2:'Gwybodaeth Eiddo.',sub:'Un UPRN. Un graff eiddo sy’n dangos ei ffynonellau.',body:'Datryswch eiddo ym Mhrydain Fawr drwy ei UPRN swyddogol, yna cysylltwch gyfesurynnau, dynodwyr OS ac - yng Nghymru a Lloegr lle mae dolenni HMLR pendant - trafodion, daliadaeth, math o eiddo, geometreg estyniad cofrestredig a gwerth dangosol.',product:'Cynnyrch',coverage:'Cwmpas',docs:'Dogfennau',workspace:'Gweithle API',pricing:'Prisiau',sources:'Ffynonellau',access:'Cael mynediad GB',start:'Cychwyn Developer',viewDocs:'Gweld dogfennau',openWorkspace:'Agor gweithle',priceTitle:'Mynediad cynhyrchu mewn GBP.',priceBody:'Tri chynllun GB hunanwasanaeth. Talu diogel drwy Stripe. Uwchraddiwch wrth i gyfaint dyfu.',proof:'Wedi ei adeiladu fel seilwaith, nid demo.'}
} as const;

function setText(el:Element|null,value:string){if(el)el.textContent=value}
function enhance(){
  const nav=document.querySelector<HTMLElement>('#nav');
  if(nav)nav.innerHTML='<a href="#platform" data-nav="product">Product</a><a href="#coverage" data-nav="coverage">Coverage</a><a href="/docs" data-nav="docs">Docs</a><a href="/workspace" data-nav="workspace">API Workspace</a><a href="#pricing" data-nav="pricing">Pricing</a><a href="#sources" data-nav="sources">Sources</a>';
  const navCta=document.querySelector<HTMLAnchorElement>('.nav-cta');if(navCta){navCta.href='#pricing';navCta.innerHTML='Get GB access <span>→</span>'}
  if(!document.querySelector('.lang-switch')){const s=document.createElement('div');s.className='lang-switch';s.innerHTML='<button class="lang-btn active" data-lang="en">EN</button><button class="lang-btn" data-lang="cy">CY</button>';navCta?.before(s)}

  const heroActions=document.querySelector<HTMLElement>('.hero-actions');if(heroActions)heroActions.innerHTML=`<a class="btn primary" id="start-plan" href="${STRIPE.developer}">Start Developer <span>→</span></a><a class="btn glass" id="docs-btn" href="/docs"><span class="code">&lt;/&gt;</span>View docs</a><a class="btn glass" id="workspace-btn" href="/workspace">Open workspace</a>`;
  const graph=document.querySelector<HTMLElement>('.graph-card');if(graph)graph.innerHTML='<div class="custom-graph-image" role="img" aria-label="Custom PropData Great Britain property graph"></div><div class="graph-links"><span>UPRN <b>10090718379</b></span><span>INSPIRE <b>56596203</b></span><span>Confidence <b>100%</b></span></div>';
  const coverageMap=document.querySelector<HTMLElement>('.coverage-map');if(coverageMap)coverageMap.innerHTML='<div class="map-title"><b>GREAT BRITAIN</b><span>Custom property intelligence visual</span></div><div class="custom-coverage-image" role="img" aria-label="Custom Great Britain property intelligence coverage visual"></div><div class="legend"><span><i class="gb"></i>GB-wide UPRN identity</span><span><i class="ew"></i>England & Wales HMLR enrichment</span></div>';
  document.querySelectorAll('#site-root svg').forEach(x=>x.remove());

  const apiCopy=document.querySelector<HTMLElement>('.api-copy');if(apiCopy&&!apiCopy.querySelector('.api-cta-row')){const row=document.createElement('div');row.className='api-cta-row';row.innerHTML='<a class="btn primary darkbtn" href="/docs">Read GB docs →</a><a class="btn outline darkoutline" href="/workspace">Open API workspace</a>';apiCopy.append(row)}

  const sources=document.querySelector<HTMLElement>('#sources');
  if(sources&&!document.querySelector('#pricing')){const pricing=document.createElement('section');pricing.className='section pricing-section';pricing.id='pricing';pricing.innerHTML=`<div class="shell"><div class="section-head light pricing-head reveal shown"><span class="kicker">LIVE STRIPE PRICING</span><h2 id="pricing-title">Production access in GBP.</h2><p id="pricing-body">Three self-serve GB plans. Secure hosted checkout by Stripe. Upgrade as volume grows.</p></div><div class="pricing-grid"><article class="price-card"><span class="plan">Developer</span><div class="price"><b>£79</b><span>/ month</span></div><p>10,000 API requests / month</p><ul><li>GB-wide UPRN identity</li><li>Linked TOID / USRN</li><li>HMLR transaction intelligence where linked</li><li>REST + MCP access</li><li>Source-aware responses</li></ul><a class="price-btn" href="${STRIPE.developer}">Start Developer</a><small>Secure Stripe checkout</small></article><article class="price-card featured"><div class="popular">MOST POPULAR</div><span class="plan">Builder</span><div class="price"><b>£249</b><span>/ month</span></div><p>50,000 API requests / month</p><ul><li>Everything in Developer</li><li>Production-volume GB access</li><li>HMLR + INSPIRE enrichment where linked</li><li>Indicative value where coverage qualifies</li><li>Priority integration support</li></ul><a class="price-btn" href="${STRIPE.builder}">Start Builder</a><small>Secure Stripe checkout</small></article><article class="price-card"><span class="plan">Scale</span><div class="price"><b>£699</b><span>/ month</span></div><p>250,000 API requests / month</p><ul><li>Everything in Builder</li><li>High-volume property intelligence</li><li>UPRN + identifier graph workflows</li><li>Advanced support</li><li>Built for production platforms</li></ul><a class="price-btn" href="${STRIPE.scale}">Start Scale</a><small>Secure Stripe checkout</small></article><article class="price-card enterprise-card"><span class="plan">Enterprise</span><div class="price"><b>Custom</b></div><p>Contracted volume and delivery</p><ul><li>Bulk / custom delivery</li><li>White-label options</li><li>Custom response contracts</li><li>Founder-led integration</li><li>Commercial licensing review</li></ul><a class="price-btn secondary" href="mailto:sales@proptechusa.ai?subject=PropData%20Great%20Britain%20Enterprise">Contact sales</a><small>sales@proptechusa.ai</small></article></div><div class="pricing-note">Live GBP recurring subscriptions. Billing address and supported tax-ID collection occur in Stripe-hosted checkout.</div></div>`;sources.before(pricing)}

  const launchActions=document.querySelector<HTMLElement>('.launch-in>div:last-child');if(launchActions)launchActions.innerHTML=`<a class="btn primary" href="${STRIPE.builder}">Start Builder →</a><a class="btn outline" href="/workspace">Open workspace</a>`;
  const footerCol=document.querySelectorAll<HTMLElement>('.footer-grid>div')[1];if(footerCol){footerCol.innerHTML='<b>Great Britain</b><a href="#platform">Property graph</a><a href="#coverage">Coverage</a><a href="/docs">API docs</a><a href="/workspace">API workspace</a><a href="#pricing">Pricing</a><a href="#sources">Sources</a>'}

  if(!document.querySelector('#checkout-success')){const q=new URLSearchParams(location.search);if(q.get('success')==='1'){const b=document.createElement('div');b.className='checkout-success';b.id='checkout-success';b.innerHTML='<div class="shell success-inner"><b>Payment received.</b><span>Your PropData Great Britain subscription is being provisioned to the checkout email.</span><button aria-label="Close">×</button></div>';document.body.prepend(b);b.querySelector('button')?.addEventListener('click',()=>b.remove())}}

  const apply=(lang:Lang)=>{const t=text[lang];document.documentElement.lang=lang==='cy'?'cy-GB':'en-GB';const h1=document.querySelector<HTMLElement>('.hero h1');if(h1)h1.innerHTML=`${t.hero1}<br><em>${t.hero2}</em>`;setText(document.querySelector('.hero h2'),t.sub);setText(document.querySelector('.hero-copy>p'),t.body);(['product','coverage','docs','workspace','pricing','sources'] as const).forEach(k=>setText(document.querySelector(`[data-nav="${k}"]`),t[k]));if(navCta){navCta.childNodes[0].textContent=t.access+' '};setText(document.querySelector('#start-plan'),t.start);const docsBtn=document.querySelector('#docs-btn');if(docsBtn)docsBtn.innerHTML='<span class="code">&lt;/&gt;</span>'+t.viewDocs;setText(document.querySelector('#workspace-btn'),t.openWorkspace);setText(document.querySelector('#pricing-title'),t.priceTitle);setText(document.querySelector('#pricing-body'),t.priceBody);setText(document.querySelector('#proof .section-head h2'),t.proof);document.querySelectorAll<HTMLButtonElement>('.lang-btn').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));localStorage.setItem('propdata-gb-lang',lang)};
  const saved=(localStorage.getItem('propdata-gb-lang')||'en') as Lang;apply(saved==='cy'?'cy':'en');document.querySelectorAll<HTMLButtonElement>('.lang-btn').forEach(b=>b.addEventListener('click',()=>apply((b.dataset.lang||'en') as Lang)));
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>queueMicrotask(enhance));else queueMicrotask(enhance);
