import './site.css';
const root=document.querySelector<HTMLDivElement>('#workspace-root')!;
const T={en:{title:'Great Britain API Workspace',sub:'Run a real UPRN lookup against production. Your key is used for this request only and is never written to localStorage.',key:'PropData API key',uprn:'UPRN',run:'Run production request',response:'Response',docs:'Docs',pricing:'Pricing',home:'Home',clear:'Clear key'},cy:{title:'Gweithle API Prydain Fawr',sub:'Rhedwch chwiliad UPRN go iawn yn erbyn cynhyrchu. Defnyddir eich allwedd ar gyfer y cais hwn yn unig ac ni chaiff ei chadw yn localStorage.',key:'Allwedd API PropData',uprn:'UPRN',run:'Rhedeg cais cynhyrchu',response:'Ymateb',docs:'Dogfennau',pricing:'Prisiau',home:'Hafan',clear:'Clirio allwedd'}} as const;
type Lang=keyof typeof T;
root.innerHTML=`<header class="sub-header"><div class="shell sub-nav"><a class="brand" href="/"><span class="brandmark"><span></span></span><span><b>PropData</b><small>GREAT BRITAIN · WORKSPACE</small></span></a><a href="/" data-k="home">Home</a><a href="/docs" data-k="docs">Docs</a><a href="/#pricing" data-k="pricing">Pricing</a><div class="lang-switch"><button class="lang-btn active" data-lang="en">EN</button><button class="lang-btn" data-lang="cy">CY</button></div></div></header><main class="sub-main"><section class="sub-hero"><div><span class="kicker">LIVE PRODUCTION EXPLORER</span><h1 data-k="title">Great Britain API Workspace</h1><p data-k="sub">Run a real UPRN lookup against production. Your key is used for this request only and is never written to localStorage.</p></div><div class="sub-art property-graph-image" role="img" aria-label="PropData GB property graph"></div></section><div class="workspace-grid"><section class="workspace-panel"><h2>GET /v1/property</h2><p>Country is locked to GB for this workspace. The request is proxied by this site so the key is not placed in the query string or committed into frontend code.</p><div class="form-row"><label data-k="key">PropData API key</label><div class="input-shell"><input id="api-key" type="password" autocomplete="off" spellcheck="false" placeholder="Enter your API key"><button id="toggle-key">Show</button></div></div><div class="form-row"><label data-k="uprn">UPRN</label><div class="input-shell"><input id="uprn" inputmode="numeric" value="10090718379" aria-label="UPRN"></div><div class="example-pills"><button data-uprn="10090718379">Wales</button><button data-uprn="100021809877">London</button><button data-uprn="100070359270">Birmingham</button><button data-uprn="129966">Bristol</button><button data-uprn="10025270278">Scotland</button></div></div><div class="request-preview mono" id="request-preview">GET /v1/property?country=GB&uprn=10090718379&enrich=standard</div><button class="run-btn" id="run" data-k="run">Run production request</button><div class="workspace-actions"><button id="clear-key" data-k="clear">Clear key</button><a href="/docs">Read contract</a><a href="/#pricing">Get access</a></div><p class="workspace-note">Security: the page does not persist your key. The same-origin function receives it in a header and forwards it to PropData. Avoid running production credentials on shared or untrusted computers.</p></section><section class="workspace-panel"><div class="response-toolbar"><b data-k="response">Response</b><span id="elapsed"></span><span class="status-pill" id="status">Ready</span></div><pre class="response-pre mono" id="response">{
  "ready": true,
  "hint": "Enter your API key and run a verified GB UPRN."
}</pre></section></div></main>`;
const keyEl=document.querySelector<HTMLInputElement>('#api-key')!;const uprnEl=document.querySelector<HTMLInputElement>('#uprn')!;const run=document.querySelector<HTMLButtonElement>('#run')!;const response=document.querySelector<HTMLElement>('#response')!;const status=document.querySelector<HTMLElement>('#status')!;const elapsed=document.querySelector<HTMLElement>('#elapsed')!;const preview=document.querySelector<HTMLElement>('#request-preview')!;
const updatePreview=()=>preview.textContent=`GET /v1/property?country=GB&uprn=${encodeURIComponent(uprnEl.value.trim())}&enrich=standard`;uprnEl.addEventListener('input',updatePreview);document.querySelectorAll<HTMLButtonElement>('[data-uprn]').forEach(b=>b.addEventListener('click',()=>{uprnEl.value=b.dataset.uprn||'';updatePreview()}));
document.querySelector('#toggle-key')?.addEventListener('click',()=>{keyEl.type=keyEl.type==='password'?'text':'password';(document.querySelector('#toggle-key') as HTMLButtonElement).textContent=keyEl.type==='password'?'Show':'Hide'});document.querySelector('#clear-key')?.addEventListener('click',()=>{keyEl.value='';keyEl.focus()});
run.addEventListener('click',async()=>{const key=keyEl.value.trim();const uprn=uprnEl.value.trim();if(!key){response.textContent=JSON.stringify({error:'API key required'},null,2);status.textContent='Missing key';return}if(!/^\d{1,20}$/.test(uprn)){response.textContent=JSON.stringify({error:'UPRN must contain digits only'},null,2);status.textContent='Invalid UPRN';return}run.disabled=true;status.textContent='Running';status.className='status-pill';response.textContent='Requesting production...';const start=performance.now();try{const r=await fetch('/api/propdata',{method:'POST',headers:{'content-type':'application/json','x-propdata-key':key},body:JSON.stringify({uprn,enrich:'standard'})});const text=await r.text();let body:any;try{body=JSON.parse(text)}catch{body={raw:text}}response.textContent=JSON.stringify(body,null,2);status.textContent=`HTTP ${r.status}`;status.className='status-pill'+(r.ok?' ok':'');if(!r.ok)response.classList.add('error-box');else response.classList.remove('error-box')}catch(err){response.textContent=JSON.stringify({error:'workspace_request_failed',message:err instanceof Error?err.message:String(err)},null,2);status.textContent='Failed';response.classList.add('error-box')}finally{elapsed.textContent=`${Math.round(performance.now()-start)} ms`;run.disabled=false}});
function lang(x:Lang){document.documentElement.lang=x==='cy'?'cy-GB':'en-GB';document.querySelectorAll<HTMLElement>('[data-k]').forEach(el=>{const k=el.dataset.k as keyof typeof T.en;const v=T[x][k];if(v)el.textContent=v});document.querySelectorAll<HTMLButtonElement>('.lang-btn').forEach(b=>b.classList.toggle('active',b.dataset.lang===x));localStorage.setItem('propdata-gb-lang',x)}const saved=(localStorage.getItem('propdata-gb-lang')||'en') as Lang;lang(saved==='cy'?'cy':'en');document.querySelectorAll<HTMLButtonElement>('.lang-btn').forEach(b=>b.addEventListener('click',()=>lang((b.dataset.lang||'en') as Lang)));
