const root=document.querySelector<HTMLDivElement>('#site-root')!;
const STRIPE={developer:'https://buy.stripe.com/4gM8wP1rUfKS4pv5sn7wA0g',builder:'https://buy.stripe.com/8x29ATgmOaqy4pvg717wA0h',scale:'https://buy.stripe.com/00w5kDfiK1U21djaMH7wA0i'};
type Lang='en'|'cy';
const copy={
  en:{
    navProduct:'Product',navCoverage:'Coverage',navDocs:'Docs',navWorkspace:'API Workspace',navPricing:'Pricing',navSources:'Sources',navAccess:'Get access',
    eyebrow:'PROPDATA GREAT BRITAIN · PRODUCTION API',heroTitle:'The property identity layer for Great Britain.',heroBody:'Resolve an official UPRN first, then attach source-aware property intelligence — linked OS identifiers, HMLR transactions, tenure, registered extents and indicative valuation where deterministic coverage exists.',start:'Start Developer — £79',workspace:'Try the API workspace',docs:'Read the docs',
    live:'LIVE · PRODUCTION READY',liveTitle:'One property contract. Coverage stays explicit.',live1:'GB-wide UPRN identity and coordinates',live2:'England & Wales HMLR depth where officially linked',live3:'No fuzzy sale-to-property joins in the launch graph',live4:'Unavailable data stays unavailable — never fabricated',
    mediaTitle:'Official identifiers in. Property intelligence out.',mediaBody:'A deliberately source-aware stack for software teams that need to know exactly what is fact, what is linked and what is unavailable.',
    devTitle:'Integrate GB property data in minutes.',devBody:'Use the same PropData property route with country=GB and an official UPRN. Keep credentials server-side and inspect coverage before using optional enrichment.',
    priceTitle:'Production pricing in GBP.',priceBody:'Real recurring Stripe plans. Start self-serve, then move into custom delivery when volume or licensing requires it.',
    finalTitle:'Build on the identifier. Not the guess.',finalBody:'Production GB property identity is live. If you are building PropTech, AI, GIS or property-data workflows, the API is ready.'
  },
  cy:{
    navProduct:'Cynnyrch',navCoverage:'Cwmpas',navDocs:'Dogfennau',navWorkspace:'Gweithle API',navPricing:'Prisiau',navSources:'Ffynonellau',navAccess:'Cael mynediad',
    eyebrow:'PROPDATA PRYDAIN FAWR · API CYNHYRCHU',heroTitle:'Haen hunaniaeth eiddo Prydain Fawr.',heroBody:'Datryswch UPRN swyddogol yn gyntaf, yna cysylltwch wybodaeth eiddo sy’n dangos ei ffynonellau — dynodwyr OS, trafodion HMLR, daliadaeth, estyniadau cofrestredig a gwerth dangosol lle mae cwmpas pendant.',start:'Cychwyn Developer — £79',workspace:'Rhoi cynnig ar y gweithle API',docs:'Darllen y dogfennau',
    live:'BYW · YN BAROD I GYNHYRCHU',liveTitle:'Un contract eiddo. Cwmpas bob amser yn glir.',live1:'Hunaniaeth UPRN a chyfesurynnau ledled Prydain Fawr',live2:'Manylder HMLR Cymru a Lloegr lle mae dolen swyddogol',live3:'Dim paru gwerthiant niwlog yn y graff lansio',live4:'Mae data nad yw ar gael yn aros felly — dim dyfalu',
    mediaTitle:'Dynodwyr swyddogol i mewn. Gwybodaeth eiddo allan.',mediaBody:'Haen ffynonellau eglur ar gyfer timau meddalwedd sydd angen gwybod beth sy’n ffaith, beth sy’n gysylltiedig a beth sydd ddim ar gael.',
    devTitle:'Integreiddio data eiddo GB mewn munudau.',devBody:'Defnyddiwch yr un llwybr eiddo PropData gyda country=GB ac UPRN swyddogol. Cadwch gymwysterau ar y gweinydd a gwiriwch gwmpas cyn defnyddio cyfoethogi dewisol.',
    priceTitle:'Prisiau cynhyrchu mewn GBP.',priceBody:'Cynlluniau Stripe cylchol go iawn. Cychwynnwch hunanwasanaeth, yna symudwch i ddarpariaeth bwrpasol pan fo cyfaint neu drwyddedu yn gofyn.',
    finalTitle:'Adeiladwch ar y dynodwr. Nid y dyfaliad.',finalBody:'Mae hunaniaeth eiddo GB cynhyrchu yn fyw. Os ydych yn adeiladu PropTech, AI, GIS neu lifoedd data eiddo, mae’r API yn barod.'
  }
} as const;
root.innerHTML=`
<a class="skip" href="#main">Skip to content</a>
<header class="topbar" id="header"><div class="shell nav-wrap">
  <a class="brand" href="/" aria-label="PropData Great Britain home"><span class="brand-mark">PD</span><span><b>PropData</b><small>by PropTechUSA.ai · GREAT BRITAIN</small></span></a>
  <button class="menu-btn" id="menu" aria-label="Toggle navigation" aria-expanded="false"><span></span><span></span><span></span></button>
  <nav id="nav"><a href="#product" data-copy="navProduct">Product</a><a href="#coverage" data-copy="navCoverage">Coverage</a><a href="/docs" data-copy="navDocs">Docs</a><a href="/workspace" data-copy="navWorkspace">API Workspace</a><a href="#pricing" data-copy="navPricing">Pricing</a><a href="#sources" data-copy="navSources">Sources</a></nav>
  <div class="lang-switch" aria-label="Language"><button class="lang-btn active" data-lang="en">EN</button><button class="lang-btn" data-lang="cy">CY</button></div>
  <a class="nav-cta" href="#pricing" data-copy="navAccess">Get access</a>
</div></header>
<main id="main">
<section class="hero" id="product"><div class="hero-image"></div><div class="hero-overlay"></div><div class="shell hero-layout">
  <div class="hero-copy"><span class="eyebrow" data-copy="eyebrow">PROPDATA GREAT BRITAIN · PRODUCTION API</span><h1 data-copy="heroTitle">The property identity layer for Great Britain.</h1><p data-copy="heroBody">Resolve an official UPRN first, then attach source-aware property intelligence — linked OS identifiers, HMLR transactions, tenure, registered extents and indicative valuation where deterministic coverage exists.</p>
    <div class="hero-actions"><a class="btn btn-primary" href="${STRIPE.developer}" data-copy="start">Start Developer — £79</a><a class="btn btn-glass" href="/workspace" data-copy="workspace">Try the API workspace</a><a class="text-link" href="/docs" data-copy="docs">Read the docs</a></div>
    <div class="hero-proof"><span><i></i>Production live</span><span>GB-wide property identity</span><span>Source-aware responses</span></div>
  </div>
  <aside class="live-card"><div class="live-state"><i></i><span data-copy="live">LIVE · PRODUCTION READY</span></div><h2 data-copy="liveTitle">One property contract. Coverage stays explicit.</h2><ul><li data-copy="live1">GB-wide UPRN identity and coordinates</li><li data-copy="live2">England & Wales HMLR depth where officially linked</li><li data-copy="live3">No fuzzy sale-to-property joins in the launch graph</li><li data-copy="live4">Unavailable data stays unavailable — never fabricated</li></ul><div class="live-metrics"><div><b>97,163</b><span>canonical HMLR transactions</span></div><div><b>176,605</b><span>identifier relationships</span></div><div><b>0</b><span>semantic mismatches</span></div></div></aside>
</div></section>
<section class="media-section"><div class="shell"><div class="section-intro"><span class="kicker">THE GB PROPERTY GRAPH</span><h2 data-copy="mediaTitle">Official identifiers in. Property intelligence out.</h2><p data-copy="mediaBody">A deliberately source-aware stack for software teams that need to know exactly what is fact, what is linked and what is unavailable.</p></div>
  <div class="media-grid">
    <article class="media-card"><div class="media-img img-identity"></div><div class="media-body"><span>01</span><h3>Property identity</h3><p>UPRN, coordinates and exact-match confidence from official OS identity infrastructure.</p></div></article>
    <article class="media-card"><div class="media-img img-transactions"></div><div class="media-body"><span>02</span><h3>Transaction history</h3><p>Recorded HMLR sales attached only when the official lookup supports a deterministic join.</p></div></article>
    <article class="media-card"><div class="media-img img-land"></div><div class="media-body"><span>03</span><h3>Tenure & registered data</h3><p>Source-aware HMLR attributes and INSPIRE relationships where publication and linkage allow.</p></div></article>
    <article class="media-card"><div class="media-img img-geometry"></div><div class="media-body"><span>04</span><h3>Spatial intelligence</h3><p>Coordinate identity and registered-extent context for mapping, GIS and due-diligence workflows.</p></div></article>
    <article class="media-card"><div class="media-img img-valuation"></div><div class="media-body"><span>05</span><h3>Indicative value</h3><p>Transparent local sale context and comp-backed market signals when coverage qualifies.</p></div></article>
    <article class="media-card"><div class="media-img img-developers"></div><div class="media-body"><span>06</span><h3>Built for developers</h3><p>One API contract, explicit coverage states, provenance and production-safe failure behaviour.</p></div></article>
  </div>
</div></section>
<section class="statbar"><div class="shell stats"><div><b>97,163</b><span>canonical HMLR transactions</span></div><div><b>176,605</b><span>transaction ↔ identifier links</span></div><div><b>174,262</b><span>reusable identity nodes</span></div><div><b>95.63%</b><span>deterministic July feed coverage</span></div><div><b>0</b><span>semantic mismatches at launch</span></div></div></section>
<section class="developer-section" id="coverage"><div class="shell dev-grid"><div class="dev-copy"><span class="kicker dark">DEVELOPER FIRST</span><h2 data-copy="devTitle">Integrate GB property data in minutes.</h2><p data-copy="devBody">Use the same PropData property route with country=GB and an official UPRN. Keep credentials server-side and inspect coverage before using optional enrichment.</p><div class="dev-actions"><a class="btn btn-dark" href="/docs">View API documentation</a><a class="btn btn-outline" href="/workspace">Open API workspace</a></div><div class="dev-badges"><span>REST</span><span>MCP</span><span>Source provenance</span><span>Coverage states</span></div></div>
  <div class="code-panel"><div class="code-head"><span>GET /v1/property</span><button id="copy-code">Copy</button></div><pre id="code-block">curl -G 'https://propdata-api-worker.sales-fd3.workers.dev/v1/property' \\
  -H 'x-api-key: $PROPDATA_API_KEY' \\
  --data-urlencode 'country=GB' \\
  --data-urlencode 'uprn=10090718379'</pre><div class="code-foot"><span>Verified production example</span><b>UPRN 10090718379</b></div></div>
  <div class="coverage-panel"><div class="coverage-image"></div><div class="coverage-copy"><span>GREAT BRITAIN COVERAGE</span><h3>Identity is national. HMLR depth is jurisdiction-aware.</h3><p>UPRN property identity covers the loaded GB layer. HMLR Price Paid and INSPIRE enrichment is specific to England & Wales and only appears where deterministic links exist.</p><a href="/docs#coverage">Read coverage contract →</a></div></div>
</div></section>
<section class="graph-section"><div class="shell graph-grid"><div class="graph-visual"></div><div class="graph-copy"><span class="kicker">IDENTITY BEFORE ENRICHMENT</span><h2>UPRN is the anchor. Every other layer keeps its provenance.</h2><p>PropData does not flatten different authorities into a mystery blob. OS identity, HMLR transactions, INSPIRE extents and PropData-derived market signals remain distinguishable in the response.</p><div class="graph-points"><span><b>UPRN</b> official property identity</span><span><b>TOID / USRN</b> linked OS identifiers</span><span><b>HMLR</b> deterministic transaction relationships</span><span><b>INSPIRE</b> registered extent relationships</span></div></div></div></section>
<section class="sources-section" id="sources"><div class="shell"><div class="source-hero"><div class="source-photo"></div><div class="source-copy"><span class="kicker">SOURCE TRANSPARENCY</span><h2>Official sources. Clear boundaries.</h2><p>Coverage is only as useful as the user’s ability to understand where a fact came from and what it means. The GB response contract keeps source attribution visible.</p></div></div>
  <div class="source-cards"><article><b>OS</b><h3>OS Open UPRN</h3><p>Great Britain property identity and official coordinates.</p></article><article><b>OS</b><h3>Open Linked Identifiers</h3><p>UPRN relationships to TOID and USRN where published.</p></article><article><b>HMLR</b><h3>Price Paid Data</h3><p>Recorded transaction facts for England & Wales.</p></article><article><b>HMLR</b><h3>Official lookup tables</h3><p>Deterministic bridges from transactions to UPRN and INSPIRE identifiers.</p></article></div>
  <div class="rights-note"><strong>Rights-aware by design.</strong><span>Restricted HMLR address fields are not exposed in the certified canonical transaction graph. INSPIRE geometry is indicative registered freehold extent context, not a legal title boundary. Indicative valuation is a market signal, not a formal appraisal.</span></div>
</div></section>
<section class="pricing-section" id="pricing"><div class="shell"><div class="section-intro centered"><span class="kicker dark">LIVE GBP PRICING</span><h2 data-copy="priceTitle">Production pricing in GBP.</h2><p data-copy="priceBody">Real recurring Stripe plans. Start self-serve, then move into custom delivery when volume or licensing requires it.</p></div>
  <div class="pricing-grid">
    <article class="price-card"><span class="plan">Developer</span><div class="price"><b>£79</b><small>/month</small></div><p>10,000 requests / month</p><ul><li>GB-wide UPRN identity</li><li>Linked identifiers</li><li>HMLR intelligence where linked</li><li>REST + MCP access</li></ul><a href="${STRIPE.developer}">Start Developer</a></article>
    <article class="price-card featured"><span class="tag">MOST POPULAR</span><span class="plan">Builder</span><div class="price"><b>£249</b><small>/month</small></div><p>50,000 requests / month</p><ul><li>Everything in Developer</li><li>Production-volume access</li><li>HMLR + INSPIRE enrichment</li><li>Priority integration support</li></ul><a href="${STRIPE.builder}">Start Builder</a></article>
    <article class="price-card"><span class="plan">Scale</span><div class="price"><b>£699</b><small>/month</small></div><p>250,000 requests / month</p><ul><li>Everything in Builder</li><li>High-volume workflows</li><li>Advanced support</li><li>Production platform scale</li></ul><a href="${STRIPE.scale}">Start Scale</a></article>
    <article class="price-card enterprise"><span class="plan">Enterprise</span><div class="price"><b>Custom</b></div><p>Contracted delivery</p><ul><li>Bulk & custom delivery</li><li>White-label options</li><li>Custom response contracts</li><li>Licensing review</li></ul><a href="mailto:sales@proptechusa.ai?subject=PropData%20Great%20Britain%20Enterprise">Contact sales</a></article>
  </div><p class="pricing-foot">Secure Stripe-hosted checkout · GBP recurring subscriptions · Enterprise pricing by contract</p>
</div></section>
<section class="use-section"><div class="shell"><div class="section-intro"><span class="kicker dark">BUILT FOR PROPERTY SYSTEMS</span><h2>One property layer, multiple production use cases.</h2></div><div class="use-grid"><article><span>01</span><h3>PropTech products</h3><p>Anchor product experiences on UPRN rather than brittle free-text address strings.</p></article><article><span>02</span><h3>AI & agent workflows</h3><p>Give systems explicit property facts, coverage states and provenance instead of invented fills.</p></article><article><span>03</span><h3>GIS & mapping</h3><p>Connect official coordinate identity and registered-extent context into spatial workflows.</p></article><article><span>04</span><h3>Portfolio intelligence</h3><p>Preserve one-to-many identifier and transaction relationships across assets.</p></article></div></div></section>
<section class="final-cta"><div class="shell final-inner"><div><span class="kicker">PROPDATA GREAT BRITAIN</span><h2 data-copy="finalTitle">Build on the identifier. Not the guess.</h2><p data-copy="finalBody">Production GB property identity is live. If you are building PropTech, AI, GIS or property-data workflows, the API is ready.</p></div><div class="final-actions"><a class="btn btn-primary" href="${STRIPE.builder}">Start Builder — £249</a><a class="btn btn-glass" href="/workspace">Open workspace</a></div></div></section>
</main>
<footer><div class="shell footer-grid"><div class="footer-brand"><a class="brand" href="/"><span class="brand-mark">PD</span><span><b>PropData</b><small>by PropTechUSA.ai</small></span></a><p>Property intelligence infrastructure for software, AI and real estate.</p></div><div><b>Great Britain</b><a href="#product">Product</a><a href="#coverage">Coverage</a><a href="/docs">Docs</a><a href="/workspace">Workspace</a><a href="#pricing">Pricing</a></div><div><b>Network</b><a href="https://propdata.proptechusa.ai/">PropData</a><a href="https://global.proptechusa.ai/">Global</a><a href="https://nz.proptechusa.ai/">New Zealand</a><a href="https://ee.proptechusa.ai/">Estonia</a></div><div><b>Company</b><a href="https://proptechusa.ai/">PropTechUSA.ai</a><a href="mailto:sales@proptechusa.ai">sales@proptechusa.ai</a></div></div><div class="shell footer-bottom"><span>© 2026 PropTechUSA.ai · PropData Great Britain</span><span>Source-aware property infrastructure</span></div></footer>`;

const menu=document.querySelector<HTMLButtonElement>('#menu')!;const nav=document.querySelector<HTMLElement>('#nav')!;menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const header=document.querySelector('#header')!;window.addEventListener('scroll',()=>header.classList.toggle('scrolled',window.scrollY>20),{passive:true});
const copyBtn=document.querySelector<HTMLButtonElement>('#copy-code')!;copyBtn.addEventListener('click',async()=>{const text=document.querySelector('#code-block')?.textContent||'';try{await navigator.clipboard.writeText(text);copyBtn.textContent='Copied';setTimeout(()=>copyBtn.textContent='Copy',1400)}catch{copyBtn.textContent='Select code'}});
function applyLang(lang:Lang){const t=copy[lang];document.documentElement.lang=lang==='cy'?'cy-GB':'en-GB';document.querySelectorAll<HTMLElement>('[data-copy]').forEach(el=>{const k=el.dataset.copy as keyof typeof t;if(t[k])el.textContent=t[k]});document.querySelectorAll<HTMLButtonElement>('.lang-btn').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));localStorage.setItem('propdata-gb-lang',lang)}
const stored=(localStorage.getItem('propdata-gb-lang')||'en') as Lang;applyLang(stored==='cy'?'cy':'en');document.querySelectorAll<HTMLButtonElement>('.lang-btn').forEach(b=>b.addEventListener('click',()=>applyLang((b.dataset.lang||'en') as Lang)));
const q=new URLSearchParams(location.search);if(q.get('success')==='1'){const notice=document.createElement('div');notice.className='purchase-notice';notice.innerHTML='<div class="shell"><b>Payment received.</b><span>Your Great Britain subscription is being provisioned to the checkout email.</span><button aria-label="Close">×</button></div>';document.body.prepend(notice);notice.querySelector('button')?.addEventListener('click',()=>notice.remove())}
